# Generated by Django 6.0.1 on 2026-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('code_1', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('code_1_type', models.TextField(blank=True, null=True)),
                ('code_2', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('code_2_type', models.TextField(blank=True, null=True)),
                ('code_3', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('code_3_type', models.TextField(blank=True, null=True)),
                ('code_4', models.TextField(blank=True, null=True)),
                ('code_4_type', models.TextField(blank=True, null=True)),
                ('code_5', models.TextField(blank=True, null=True)),
                ('code_5_type', models.TextField(blank=True, null=True)),
                ('code_6', models.TextField(blank=True, null=True)),
                ('code_6_type', models.TextField(blank=True, null=True)),
                ('setting', models.TextField(blank=True, null=True)),
                ('drug_unit_of_measurement', models.TextField(blank=True, null=True)),
                ('drug_type_of_measurement', models.TextField(blank=True, null=True)),
                ('standard_charge_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_charge_discounted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payer_name', models.TextField(blank=True, null=True)),
                ('plan_name', models.TextField(blank=True, null=True)),
                ('modifiers', models.TextField(blank=True, null=True)),
                ('standard_charge_negotiated_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_charge_negotiated_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_charge_negotiated_algorithm', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_charge_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_charge_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('standard_charge_methodology', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('additional_generic_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital_prices',
                'managed': True,
            },
        ),
    ]
